language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - travis_retry composer install --no-interaction --prefer-source --dev
  - travis_retry phpenv rehash

script:
  - ./vendor/bin/phpcs -sp --standard=psr2 src
  - ./vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/coverage/log/coverage.xml

notifications:
  email: false
